language: rust
before_script:
  - rustup component add rustfmt
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - cargo build
  - cargo test
  - cargo fmt -- --check
