[package]
name = "rememberthemilk"
version = "0.1.0"
authors = ["Chris Emerson <github@mail.nosreme.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
reqwest = "0.10"
serde = "1.0"
failure = "*"
md5 = "0.7"