[package]
name = "rememberthemilk"
version = "0.1.0"
authors = ["Chris Emerson <github@mail.nosreme.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
reqwest = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "*"
failure = "*"
md5 = "0.7"

[dev-dependencies]
confy = "0.3"
